/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    A4CRatingTab: typeof import('./src/components/college/tabs/A4CRatingTab.vue')['default']
    AdmitChanceComponent: typeof import('./src/components/AdmitChanceComponent.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppMenu: typeof import('./src/components/AppMenu.vue')['default']
    AuthModal: typeof import('./src/components/AuthModal.vue')['default']
    ChancingTab: typeof import('./src/components/college/tabs/ChancingTab.vue')['default']
    CollegeComparison: typeof import('./src/components/CollegeComparison.vue')['default']
    CostTab: typeof import('./src/components/college/tabs/CostTab.vue')['default']
    ExplorePage: typeof import('./src/components/explorePage.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/home.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MajorsTab: typeof import('./src/components/college/tabs/MajorsTab.vue')['default']
    OverviewTab: typeof import('./src/components/college/tabs/OverviewTab.vue')['default']
    ProfileEdit: typeof import('./src/components/ProfileEdit.vue')['default']
    ProfilePage: typeof import('./src/components/profilePage.vue')['default']
    ProfileSummaryComponent: typeof import('./src/components/ProfileSummaryComponent.vue')['default']
    ProfileView: typeof import('./src/components/ProfileView.vue')['default']
    RecommendationComponent: typeof import('./src/components/RecommendationComponent.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Schools: typeof import('./src/components/Schools.vue')['default']
    SettingsPage: typeof import('./src/components/settingsPage.vue')['default']
  }
}
